package prasad.vennam.moneypilot.ui.loans

import prasad.vennam.moneypilot.data.AppLinks

object ShareFormatter {

    fun buildLoanCalculationShareText(
        currencySymbol: String,
        amount: String,
        interestRate: String,
        tenure: String,
        isTenureInYears: Boolean,
        monthlyEmi: String,
        totalInterest: String,
        totalPayable: String,
        loanEndDate: String,
    ): String {

        val tenureText =
            "$tenure ${if (isTenureInYears) "Years" else "Months"}"

        return buildString {

            appendLine("💰 MONEYPILOT")
            appendLine("Loan EMI Report")
            appendLine()

            appendLine("━━━━━━━━━━━━━━━━━━━━")
            appendLine()

            appendLine("🏦 Loan Amount")
            appendLine("$currencySymbol$amount")
            appendLine()

            appendLine("📈 Interest Rate")
            appendLine("$interestRate% p.a.")
            appendLine()

            appendLine("📅 Loan Tenure")
            appendLine(tenureText)
            appendLine()

            appendLine("━━━━━━━━━━━━━━━━━━━━")
            appendLine()

            appendLine("💳 Monthly EMI")
            appendLine(monthlyEmi)
            appendLine()

            appendLine("💰 Total Interest")
            appendLine(totalInterest)
            appendLine()

            appendLine("🏁 Total Payable")
            appendLine(totalPayable)
            appendLine()

            appendLine("📆 Loan Ends")
            appendLine(loanEndDate)
            appendLine()

            appendLine("━━━━━━━━━━━━━━━━━━━━")
            appendLine()

            appendLine("Generated by MoneyPilot")
            appendLine("Track Expenses • Budgets • Loans • Investments")
            appendLine()

            appendLine(AppLinks.PLAY_STORE)
        }
    }
}